<?php

namespace UserBundle\Repository;

/**
 * UndertasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UndertasksRepository extends \Doctrine\ORM\EntityRepository
{
}
