<?php

namespace UserBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function loadUserByUsername($username) {
        return $this->getEntityManager()
            ->createQuery('SELECT u FROM
         UserBundle:User u
         WHERE u.username = :username
         OR u.email = :username')
            ->setParameters(array(
                'username' => $username
            ))
            ->getOneOrNullResult();
    }

    public function refreshUser(UserInterface $user) {
        return $this->loadUserByUsername($user->getUsername());
    }
}
